# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 686)
        MainWindow.setStyleSheet("#bg{\n"
"background-color:#FEFDFF;\n"
"    border: 2px solid #F7F7F7;\n"
"\n"
"}\n"
"#mainBar\n"
"{\n"
"background-color:#F7F7F7;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QWidget{\n"
"    color: rgb(40, 44, 52);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-right: 1px solid #DCDCDC;\n"
"    background-color:transparent;\n"
"    text-align: center;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #DCDCDC;\n"
"    \n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding-left: 5px;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #1159A8;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid gray;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding-left: 10px;\n"
"    background-color: white;\n"
"    selection-background-color: #1159A8;\n"
"    selection-color: white;\n"
"    height: 25px;  /* Adjust height */\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QComboBox:hover {\n"
"    border: 2px solid gray;\n"
"}")
        self.bg = QtWidgets.QWidget(MainWindow)
        self.bg.setObjectName("bg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bg)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.bg)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 53))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 53))
        self.frame_6.setStyleSheet("background-color:#1159A8;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("font: bold 14pt \"Arial\";\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_6)
        self.topBar = QtWidgets.QFrame(self.bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBar.sizePolicy().hasHeightForWidth())
        self.topBar.setSizePolicy(sizePolicy)
        self.topBar.setMinimumSize(QtCore.QSize(0, 40))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.topBar.setStyleSheet("font: 75 11pt \"Arial\";")
        self.topBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLicensePlate = QtWidgets.QPushButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLicensePlate.sizePolicy().hasHeightForWidth())
        self.btnLicensePlate.setSizePolicy(sizePolicy)
        self.btnLicensePlate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLicensePlate.setObjectName("btnLicensePlate")
        self.horizontalLayout.addWidget(self.btnLicensePlate)
        self.btnPhoneLookup = QtWidgets.QPushButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPhoneLookup.sizePolicy().hasHeightForWidth())
        self.btnPhoneLookup.setSizePolicy(sizePolicy)
        self.btnPhoneLookup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPhoneLookup.setObjectName("btnPhoneLookup")
        self.horizontalLayout.addWidget(self.btnPhoneLookup)
        self.btnZipLookup = QtWidgets.QPushButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZipLookup.sizePolicy().hasHeightForWidth())
        self.btnZipLookup.setSizePolicy(sizePolicy)
        self.btnZipLookup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnZipLookup.setObjectName("btnZipLookup")
        self.horizontalLayout.addWidget(self.btnZipLookup)
        self.verticalLayout.addWidget(self.topBar)
        self.frame = QtWidgets.QFrame(self.bg)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("color: red;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.mainBar = QtWidgets.QFrame(self.bg)
        self.mainBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBar.setObjectName("mainBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBar)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainBar)
        self.stackedWidget.setObjectName("stackedWidget")
        self.licensePlatePage = QtWidgets.QWidget()
        self.licensePlatePage.setObjectName("licensePlatePage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.licensePlatePage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.licensePlatePage)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("font: bold 14pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.licensePlatePage)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plate_entry = QtWidgets.QLineEdit(self.frame_5)
        self.plate_entry.setMinimumSize(QtCore.QSize(0, 30))
        self.plate_entry.setStyleSheet("")
        self.plate_entry.setObjectName("plate_entry")
        self.gridLayout_3.addWidget(self.plate_entry, 1, 1, 1, 1)
        self.state_dropdown = QtWidgets.QComboBox(self.frame_5)
        self.state_dropdown.setMinimumSize(QtCore.QSize(0, 30))
        self.state_dropdown.setObjectName("state_dropdown")
        self.gridLayout_3.addWidget(self.state_dropdown, 3, 1, 1, 1)
        self.dump_label = QtWidgets.QLabel(self.frame_5)
        self.dump_label.setObjectName("dump_label")
        self.gridLayout_3.addWidget(self.dump_label, 1, 0, 1, 1)
        self.ndk_label = QtWidgets.QLabel(self.frame_5)
        self.ndk_label.setObjectName("ndk_label")
        self.gridLayout_3.addWidget(self.ndk_label, 3, 0, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.frame_5)
        self.search_button.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_button.setFont(font)
        self.search_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#1159A8;\n"
"color:white;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:#146CD0;\n"
"}")
        self.search_button.setObjectName("search_button")
        self.gridLayout_3.addWidget(self.search_button, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(self.licensePlatePage)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 192))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.result_listbox = QtWidgets.QListWidget(self.frame_2)
        self.result_listbox.setStyleSheet("padding:0px;")
        self.result_listbox.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_listbox.setObjectName("result_listbox")
        self.verticalLayout_4.addWidget(self.result_listbox)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.licensePlatePage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(-1, 5, -1, 11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vinTable = QtWidgets.QTableWidget(self.frame_3)
        self.vinTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.vinTable.setObjectName("vinTable")
        self.vinTable.setColumnCount(0)
        self.vinTable.setRowCount(0)
        self.verticalLayout_5.addWidget(self.vinTable)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.licensePlatePage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setStyleSheet("font: bold 14pt \"Arial\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_4.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.phone_entry = QtWidgets.QLineEdit(self.frame_9)
        self.phone_entry.setMinimumSize(QtCore.QSize(0, 30))
        self.phone_entry.setStyleSheet("")
        self.phone_entry.setObjectName("phone_entry")
        self.gridLayout_4.addWidget(self.phone_entry, 1, 1, 1, 1)
        self.dump_label_2 = QtWidgets.QLabel(self.frame_9)
        self.dump_label_2.setObjectName("dump_label_2")
        self.gridLayout_4.addWidget(self.dump_label_2, 1, 0, 1, 1)
        self.search_button_2 = QtWidgets.QPushButton(self.frame_9)
        self.search_button_2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_button_2.setFont(font)
        self.search_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#1159A8;\n"
"color:white;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:#146CD0;\n"
"}")
        self.search_button_2.setObjectName("search_button_2")
        self.gridLayout_4.addWidget(self.search_button_2, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.page_2)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 192))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.phoneList = QtWidgets.QListWidget(self.frame_8)
        self.phoneList.setStyleSheet("padding:0px;")
        self.phoneList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.phoneList.setObjectName("phoneList")
        self.verticalLayout_7.addWidget(self.phoneList)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.page_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(-1, 5, -1, 11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.phoneTable = QtWidgets.QTableWidget(self.frame_10)
        self.phoneTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.phoneTable.setObjectName("phoneTable")
        self.phoneTable.setColumnCount(0)
        self.phoneTable.setRowCount(0)
        self.verticalLayout_8.addWidget(self.phoneTable)
        self.verticalLayout_9.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setStyleSheet("font: bold 14pt \"Arial\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(self.page)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_5.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dump_label_3 = QtWidgets.QLabel(self.frame_13)
        self.dump_label_3.setObjectName("dump_label_3")
        self.gridLayout_5.addWidget(self.dump_label_3, 1, 0, 1, 1)
        self.zip_entry = QtWidgets.QLineEdit(self.frame_13)
        self.zip_entry.setMinimumSize(QtCore.QSize(0, 30))
        self.zip_entry.setStyleSheet("")
        self.zip_entry.setObjectName("zip_entry")
        self.gridLayout_5.addWidget(self.zip_entry, 1, 1, 1, 1)
        self.search_button_3 = QtWidgets.QPushButton(self.frame_13)
        self.search_button_3.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_button_3.setFont(font)
        self.search_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#1159A8;\n"
"color:white;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:#146CD0;\n"
"}")
        self.search_button_3.setObjectName("search_button_3")
        self.gridLayout_5.addWidget(self.search_button_3, 3, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.page)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 192))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.zipList = QtWidgets.QListWidget(self.frame_12)
        self.zipList.setStyleSheet("padding:0px;")
        self.zipList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.zipList.setObjectName("zipList")
        self.verticalLayout_10.addWidget(self.zipList)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.frame_14 = QtWidgets.QFrame(self.page)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setContentsMargins(-1, 5, -1, 11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.zipTable = QtWidgets.QTableWidget(self.frame_14)
        self.zipTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.zipTable.setObjectName("zipTable")
        self.zipTable.setColumnCount(0)
        self.zipTable.setRowCount(0)
        self.verticalLayout_11.addWidget(self.zipTable)
        self.verticalLayout_12.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.mainBar)
        MainWindow.setCentralWidget(self.bg)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Big R Ranch Security"))
        self.label_2.setText(_translate("MainWindow", "Big R Ranch Security"))
        self.btnLicensePlate.setText(_translate("MainWindow", "License Plate Lookup"))
        self.btnPhoneLookup.setText(_translate("MainWindow", "Phone Number Lookup"))
        self.btnZipLookup.setText(_translate("MainWindow", "Zip Code Lookup"))
        self.label.setText(_translate("MainWindow", "License Plate Lookup"))
        self.dump_label.setText(_translate("MainWindow", "Plate:"))
        self.ndk_label.setText(_translate("MainWindow", "State:"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "Phone Number Lookup"))
        self.dump_label_2.setText(_translate("MainWindow", "Phone Number:"))
        self.search_button_2.setText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "Zip Code Lookup"))
        self.dump_label_3.setText(_translate("MainWindow", "Zip Code:"))
        self.search_button_3.setText(_translate("MainWindow", "Search"))
